package com.model;

// Generated 27 déc. 2013 02:10:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Arrangement generated by hbm2java
 */
@Entity
@Table(name = "arrangement", catalog = "comparateur")
public class Arrangement implements java.io.Serializable {

	private Integer idArrangement;
	private String libelleArrangement;
	private Set<Offre> offres = new HashSet<Offre>(0);
	

	public Arrangement() {
	}

	public Arrangement(String libelleArrangement) {
		this.libelleArrangement = libelleArrangement;
	}

	public Arrangement(String libelleArrangement, Set offres) {
		this.libelleArrangement = libelleArrangement;
		this.offres = offres;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Arrangement", unique = true, nullable = false)
	public Integer getIdArrangement() {
		return this.idArrangement;
	}

	public void setIdArrangement(Integer idArrangement) {
		this.idArrangement = idArrangement;
	}

	@Column(name = "libelle_arrangement", nullable = false, length = 100)
	public String getLibelleArrangement() {
		return this.libelleArrangement;
	}

	public void setLibelleArrangement(String libelleArrangement) {
		this.libelleArrangement = libelleArrangement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arrangement")
	public Set<Offre> getOffres() {
		return this.offres;
	}

	public void setOffres(Set<Offre> offres) {
		this.offres = offres;
	}

	

}
