package com.model;

// Generated 27 déc. 2013 02:10:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel", catalog = "comparateur")
public class Hotel implements java.io.Serializable {

	private Integer idHotel;
	private Ville ville;
	private String nomHotel;
	private String categorie;
	private String adresse;
	private Set<Disponibilite> disponibilites = new HashSet<Disponibilite>(0);
	
	private Set<Offre> offres = new HashSet<Offre>(0);
	

	public Hotel() {
	}

	public Hotel(Ville ville, String nomHotel, String categorie) {
		this.ville = ville;
		this.nomHotel = nomHotel;
		this.categorie = categorie;
	}

	public Hotel(Ville ville, String nomHotel, String categorie,
			String adresse, Set<Disponibilite> disponibilites,
			Set<Offre> offres) {
		this.ville = ville;
		this.nomHotel = nomHotel;
		this.categorie = categorie;
		this.adresse = adresse;
		this.disponibilites = disponibilites;
		
		this.offres = offres;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_hotel", unique = true, nullable = false)
	public Integer getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(Integer idHotel) {
		this.idHotel = idHotel;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_ville", nullable = false)
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@Column(name = "nom_hotel", nullable = false)
	public String getNomHotel() {
		return this.nomHotel;
	}

	public void setNomHotel(String nomHotel) {
		this.nomHotel = nomHotel;
	}

	@Column(name = "categorie", nullable = false)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "adresse")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Disponibilite> getDisponibilites() {
		return this.disponibilites;
	}

	public void setDisponibilites(Set<Disponibilite> disponibilites) {
		this.disponibilites = disponibilites;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Offre> getOffres() {
		return this.offres;
	}

	public void setOffres(Set<Offre> offres) {
		this.offres = offres;
	}

	
}
