package com.model;

// Generated 27 déc. 2013 02:10:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OffreId generated by hbm2java
 */
@Embeddable
public class OffreId implements java.io.Serializable {

	private int idHotel;
	private int idAgence;
	private int idArrangement;
	private int idTypeChambre;

	public OffreId() {
	}

	public OffreId(int idHotel, int idAgence, int idArrangement,
			int idTypeChambre) {
		this.idHotel = idHotel;
		this.idAgence = idAgence;
		this.idArrangement = idArrangement;
		this.idTypeChambre = idTypeChambre;
	}

	@Column(name = "id_hotel", nullable = false)
	public int getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(int idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "Id_agence", nullable = false)
	public int getIdAgence() {
		return this.idAgence;
	}

	public void setIdAgence(int idAgence) {
		this.idAgence = idAgence;
	}

	@Column(name = "Id_Arrangement", nullable = false)
	public int getIdArrangement() {
		return this.idArrangement;
	}

	public void setIdArrangement(int idArrangement) {
		this.idArrangement = idArrangement;
	}

	@Column(name = "id_type_chambre", nullable = false)
	public int getIdTypeChambre() {
		return this.idTypeChambre;
	}

	public void setIdTypeChambre(int idTypeChambre) {
		this.idTypeChambre = idTypeChambre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OffreId))
			return false;
		OffreId castOther = (OffreId) other;

		return (this.getIdHotel() == castOther.getIdHotel())
				&& (this.getIdAgence() == castOther.getIdAgence())
				&& (this.getIdArrangement() == castOther.getIdArrangement())
				&& (this.getIdTypeChambre() == castOther.getIdTypeChambre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHotel();
		result = 37 * result + this.getIdAgence();
		result = 37 * result + this.getIdArrangement();
		result = 37 * result + this.getIdTypeChambre();
		return result;
	}

}
