package com.model;

// Generated 27 déc. 2013 02:10:47 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Offre generated by hbm2java
 */
@Entity
@Table(name = "offre", catalog = "comparateur")
public class Offre implements java.io.Serializable {

	private OffreId id;
	private SiteAgence siteAgence;
	private Arrangement arrangement;
	private TypeChambre typeChambre;
	private Hotel hotel;
	private Double prix;
	private String promotionEventuelle;

	public Offre() {
	}

	public Offre(OffreId id, SiteAgence siteAgence, Arrangement arrangement,
			TypeChambre typeChambre, Hotel hotel, Double prix) {
		this.id = id;
		this.siteAgence = siteAgence;
		this.arrangement = arrangement;
		this.typeChambre = typeChambre;
		this.hotel = hotel;
		this.prix = prix;
	}

	public Offre(OffreId id, SiteAgence siteAgence, Arrangement arrangement,
			TypeChambre typeChambre, Hotel hotel, Double prix,
			String promotionEventuelle) {
		this.id = id;
		this.siteAgence = siteAgence;
		this.arrangement = arrangement;
		this.typeChambre = typeChambre;
		this.hotel = hotel;
		this.prix = prix;
		this.promotionEventuelle = promotionEventuelle;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idHotel", column = @Column(name = "id_hotel", nullable = false)),
			@AttributeOverride(name = "idAgence", column = @Column(name = "Id_agence", nullable = false)),
			@AttributeOverride(name = "idArrangement", column = @Column(name = "Id_Arrangement", nullable = false)),
			@AttributeOverride(name = "idTypeChambre", column = @Column(name = "id_type_chambre", nullable = false)) })
	public OffreId getId() {
		return this.id;
	}

	public void setId(OffreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_agence", nullable = false, insertable = false, updatable = false)
	public SiteAgence getSiteAgence() {
		return this.siteAgence;
	}

	public void setSiteAgence(SiteAgence siteAgence) {
		this.siteAgence = siteAgence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Arrangement", nullable = false, insertable = false, updatable = false)
	public Arrangement getArrangement() {
		return this.arrangement;
	}

	public void setArrangement(Arrangement arrangement) {
		this.arrangement = arrangement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_chambre", nullable = false, insertable = false, updatable = false)
	public TypeChambre getTypeChambre() {
		return this.typeChambre;
	}

	public void setTypeChambre(TypeChambre typeChambre) {
		this.typeChambre = typeChambre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hotel", nullable = false, insertable = false, updatable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "Prix", nullable = false, length = 30)
	public Double getPrix() {
		return this.prix;
	}

	public void setPrix(Double prix) {
		this.prix = prix;
	}

	@Column(name = "Promotion_eventuelle")
	public String getPromotionEventuelle() {
		return this.promotionEventuelle;
	}

	public void setPromotionEventuelle(String promotionEventuelle) {
		this.promotionEventuelle = promotionEventuelle;
	}

}
