package com.model;

// Generated 27 déc. 2013 02:10:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays", catalog = "comparateur")
public class Pays implements java.io.Serializable {

	private Integer idPays;
	private String nomPays;
	private Set<Ville> villes = new HashSet<Ville>(0);
	

	public Pays() {
	}

	public Pays(String nomPays) {
		this.nomPays = nomPays;
	}

	public Pays(String nomPays, Set villes) {
		this.nomPays = nomPays;
		this.villes = villes;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Pays", unique = true, nullable = false)
	public Integer getIdPays() {
		return this.idPays;
	}

	public void setIdPays(Integer idPays) {
		this.idPays = idPays;
	}

	@Column(name = "Nom_pays", nullable = false)
	public String getNomPays() {
		return this.nomPays;
	}

	public void setNomPays(String nomPays) {
		this.nomPays = nomPays;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "pays")
	public Set<Ville> getVilles() {
		return this.villes;
	}

	public void setVilles(Set<Ville> villes) {
		this.villes = villes;
	}

	
}
