package com.model;

// Generated 27 déc. 2013 02:10:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SiteAgence generated by hbm2java
 */
@Entity
@Table(name = "site_agence", catalog = "comparateur")
public class SiteAgence implements java.io.Serializable {

	private Integer idAgence;
	private String nomAgence;
	private String url;
	private String adresse;
	private Set<Offre> offres = new HashSet<Offre>(0);
	

	public SiteAgence() {
	}

	public SiteAgence(String nomAgence, String url, String adresse) {
		this.nomAgence = nomAgence;
		this.url = url;
		this.adresse = adresse;
	}

	public SiteAgence(String nomAgence, String url, String adresse, Set<Offre> offres
			) {
		this.nomAgence = nomAgence;
		this.url = url;
		this.adresse = adresse;
		this.offres = offres;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_agence", unique = true, nullable = false)
	public Integer getIdAgence() {
		return this.idAgence;
	}

	public void setIdAgence(Integer idAgence) {
		this.idAgence = idAgence;
	}

	@Column(name = "NomAgence", nullable = false)
	public String getNomAgence() {
		return this.nomAgence;
	}

	public void setNomAgence(String nomAgence) {
		this.nomAgence = nomAgence;
	}

	@Column(name = "URL", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "Adresse", nullable = false)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siteAgence")
	public Set<Offre> getOffres() {
		return this.offres;
	}

	public void setOffres(Set<Offre> offres) {
		this.offres = offres;
	}

	
}
